#!/usr/bin/env python3
"""Generate a PDF report of changes made to the Orator codebase (reportlab)."""
from datetime import date
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer, ListFlowable,
    ListItem, Preformatted, HRFlowable, Table, TableStyle,
)

PURPLE = HexColor("#7c3aed")
DARK = HexColor("#18181b")
GREY = HexColor("#3f3f46")
LIGHT = HexColor("#8a8a92")
CODE_BG = HexColor("#f4f4f7")

styles = getSampleStyleSheet()
H1 = ParagraphStyle("H1", parent=styles["Heading1"], fontName="Helvetica-Bold",
                    fontSize=15, textColor=PURPLE, spaceBefore=14, spaceAfter=6, leading=18)
H2 = ParagraphStyle("H2", parent=styles["Heading2"], fontName="Helvetica-Bold",
                    fontSize=11.5, textColor=DARK, spaceBefore=8, spaceAfter=3, leading=14)
BODY = ParagraphStyle("Body", parent=styles["Normal"], fontName="Helvetica",
                      fontSize=10, textColor=GREY, leading=14, spaceAfter=4, alignment=TA_LEFT)
META = ParagraphStyle("Meta", parent=BODY, fontSize=10.5, textColor=GREY, leading=15, spaceAfter=2)
SMALL = ParagraphStyle("Small", parent=BODY, fontSize=8.5, textColor=LIGHT)
CODE = ParagraphStyle("Code", parent=styles["Code"], fontName="Courier", fontSize=8.5,
                      textColor=HexColor("#3c3c46"), leading=11, backColor=CODE_BG,
                      borderPadding=6, leftIndent=4, spaceBefore=2, spaceAfter=8)
TITLE = ParagraphStyle("Title", parent=styles["Title"], fontName="Helvetica-Bold",
                       fontSize=28, textColor=DARK, leading=32, spaceAfter=2)
SUB = ParagraphStyle("Sub", parent=styles["Normal"], fontName="Helvetica-Bold",
                     fontSize=15, textColor=PURPLE, leading=20, spaceAfter=10)


def bullets(items):
    return ListFlowable(
        [ListItem(Paragraph(t, BODY), leftIndent=10, value="•") for t in items],
        bulletType="bullet", bulletColor=PURPLE, bulletFontSize=9, leftIndent=12, spaceBefore=2, spaceAfter=6,
    )


def code_block(text):
    return Preformatted(text, CODE)


def on_page(canvas, doc):
    canvas.saveState()
    if doc.page > 1:
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(LIGHT)
        canvas.drawString(20 * mm, A4[1] - 12 * mm, "Orator — Code Review & Maintenance Report")
        canvas.drawRightString(A4[0] - 20 * mm, A4[1] - 12 * mm, f"Page {doc.page}")
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(LIGHT)
    canvas.drawCentredString(A4[0] / 2, 12 * mm,
                             "Generated by Claude Code  •  branch: claude/relaxed-sagan-reg96i")
    canvas.restoreState()


doc = BaseDocTemplate("/home/user/speech-analyzer2/Orator-Change-Report.pdf", pagesize=A4,
                      leftMargin=20 * mm, rightMargin=20 * mm, topMargin=20 * mm, bottomMargin=20 * mm)
frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="main")
doc.addPageTemplates([PageTemplate(id="all", frames=[frame], onPage=on_page)])

S = []

# ---- Title ----
S.append(Spacer(1, 30 * mm))
logo = Table([[ "" ]], colWidths=[14 * mm], rowHeights=[14 * mm])
logo.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), PURPLE),
                          ("ROUNDEDCORNERS", [4, 4, 4, 4])]))
S.append(logo)
S.append(Spacer(1, 6 * mm))
S.append(Paragraph("Orator", TITLE))
S.append(Paragraph("Code Review &amp; Maintenance Report", SUB))
S.append(Paragraph(f"Date: {date.today().isoformat()}", META))
S.append(Paragraph("Repository: mickhatzikostas220-design/speech-analyzer2", META))
S.append(Paragraph("Branch: claude/relaxed-sagan-reg96i", META))
S.append(Paragraph("Commits in this pass: 5", META))
S.append(Spacer(1, 8 * mm))
S.append(Paragraph(
    "This report documents a review-and-fix pass over the Orator web application "
    "(a Next.js 14 / TypeScript / Supabase app for fMRI-based neural speech analysis). "
    "The goal was to find and fix anything across the site that needed attention. Every "
    "change was verified with a full production build (<font face='Courier'>next build</font>) "
    "and a lint pass before being committed.", BODY))

S.append(Paragraph("Headline result", H2))
S.append(bullets([
    "Fixed a production build-breaking bug — the app would not build for deployment before this pass.",
    "Established a working ESLint setup and fixed all lint errors.",
    "Unified the product brand name (removed leftover &lsquo;ACA&rsquo; references in user-facing emails and the AI chat assistant).",
    "Added a missing favicon / app icon and richer page metadata.",
    "Removed a committed build-cache file from version control.",
]))

from reportlab.platypus import PageBreak
S.append(PageBreak())

# ---- 1 ----
S.append(Paragraph("1. Build-breaking bug: module-level OpenAI client", H1))
S.append(Paragraph("Severity: HIGH &nbsp;|&nbsp; Files: lib/openai.ts, app/api/compare-report/route.ts", SMALL))
S.append(Paragraph("Problem", H2))
S.append(Paragraph(
    "Both files created the OpenAI client at module scope "
    "(<font face='Courier'>new OpenAI({...})</font>). During "
    "<font face='Courier'>next build</font>, Next.js evaluates route modules while collecting "
    "page data; if <font face='Courier'>OPENAI_API_KEY</font> is not set at that moment the "
    "constructor throws and aborts the whole build with &lsquo;The OPENAI_API_KEY environment "
    "variable is missing or empty&rsquo;. The build failed outright at /api/compare-report.", BODY))
S.append(Paragraph("Fix", H2))
S.append(Paragraph(
    "Moved client construction to lazy initialization so it runs at request time, not at "
    "import/build time. <font face='Courier'>lib/openai.ts</font> now uses a cached "
    "<font face='Courier'>getOpenAI()</font> helper; the compare-report route constructs the "
    "client inside the POST handler.", BODY))
S.append(code_block(
    "let _openai = null;\n"
    "function getOpenAI() {\n"
    "  if (!_openai) _openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });\n"
    "  return _openai;\n"
    "}"))
S.append(Paragraph("Verification", H2))
S.append(Paragraph("<font face='Courier'>next build</font> now completes: &lsquo;Compiled "
                   "successfully&rsquo; and &lsquo;Generating static pages (21/21)&rsquo;.", BODY))

# ---- 2 ----
S.append(Paragraph("2. ESLint configuration + lint errors", H1))
S.append(Paragraph("Severity: MEDIUM &nbsp;|&nbsp; Files: .eslintrc.json (new), package.json, 5 page files", SMALL))
S.append(Paragraph("Problem", H2))
S.append(Paragraph(
    "The project had no ESLint configuration, so <font face='Courier'>npm run lint</font> "
    "dropped into an interactive setup prompt and could not run non-interactively. Several "
    "pages also contained unescaped quotes/apostrophes in JSX "
    "(<font face='Courier'>react/no-unescaped-entities</font>).", BODY))
S.append(Paragraph("Fix", H2))
S.append(bullets([
    "Added <font face='Courier'>.eslintrc.json</font> extending next/core-web-vitals.",
    "Installed the missing @typescript-eslint plugin so existing inline disable directives resolve, and turned off the noisy no-explicit-any rule for this codebase.",
    "Escaped quotes/apostrophes in the editor, history, signup, request-access and request-access/success pages.",
]))
S.append(Paragraph("Verification", H2))
S.append(Paragraph("<font face='Courier'>npm run lint</font> now runs clean — only two "
                   "pre-existing <font face='Courier'>&lt;img&gt;</font> performance warnings "
                   "remain, which do not fail the build.", BODY))

S.append(PageBreak())

# ---- 3 ----
S.append(Paragraph("3. Brand-name inconsistency: &lsquo;ACA&rsquo; → &lsquo;Orator&rsquo;", H1))
S.append(Paragraph("Severity: MEDIUM (user-facing) &nbsp;|&nbsp; Files: components/Navbar.tsx, "
                   "lib/email.ts, app/api/analyses/[id]/chat/route.ts", SMALL))
S.append(Paragraph("Problem", H2))
S.append(Paragraph(
    "The product is named &lsquo;Orator&rsquo; in the README, page titles and auth screens, "
    "but several places still showed a prior name, &lsquo;ACA&rsquo;. This was visible to end "
    "users: the top-nav logo, all three transactional emails (access-request notification, "
    "approval, rejection), and the identity of the in-app AI chat assistant.", BODY))
S.append(Paragraph("Fix", H2))
S.append(bullets([
    "Navbar logo text: ACA → Orator.",
    "lib/email.ts: sender name, body copy and footers across all three emails.",
    "Chat assistant system prompt now reads &lsquo;You are Orator&rsquo;s speech analysis assistant&rsquo;.",
]))
S.append(Paragraph("A repository-wide search confirms no &lsquo;ACA&rsquo; references remain in "
                   "app / lib / components.", BODY))

# ---- 4 ----
S.append(Paragraph("4. Missing favicon and thin metadata", H1))
S.append(Paragraph("Severity: LOW &nbsp;|&nbsp; Files: app/icon.svg (new), app/layout.tsx", SMALL))
S.append(Paragraph("Problem", H2))
S.append(Paragraph(
    "The site shipped no favicon / app icon (no public/ directory, no app/icon). Page "
    "metadata was minimal — only a title and description, with no metadataBase, social "
    "cards or robots policy.", BODY))
S.append(Paragraph("Fix", H2))
S.append(bullets([
    "Added <font face='Courier'>app/icon.svg</font> — a gradient brand mark matching the in-app logo, auto-detected by Next.js.",
    "Expanded root metadata: metadataBase, a title template, OpenGraph + Twitter cards, and robots index:false / follow:false (appropriate because Orator is an invite-only, private app that should not be indexed).",
]))

# ---- 5 ----
S.append(Paragraph("5. Build cache committed to git", H1))
S.append(Paragraph("Severity: LOW &nbsp;|&nbsp; Files: .gitignore, tsconfig.tsbuildinfo (removed)", SMALL))
S.append(Paragraph("Problem", H2))
S.append(Paragraph(
    "<font face='Courier'>tsconfig.tsbuildinfo</font> — a ~115 KB machine-specific "
    "TypeScript incremental build cache — was tracked in version control, causing noisy "
    "diffs and potential merge conflicts.", BODY))
S.append(Paragraph("Fix", H2))
S.append(Paragraph("Added <font face='Courier'>*.tsbuildinfo</font> to .gitignore and removed "
                   "the file from tracking (<font face='Courier'>git rm --cached</font>).", BODY))

S.append(PageBreak())

# ---- Healthy ----
S.append(Paragraph("Areas reviewed and found healthy", H1))
S.append(Paragraph("The following were inspected and required no changes:", BODY))
S.append(bullets([
    "Auth middleware (route protection / redirects).",
    "Upload flow (UploadZone), including timeout handling and file validation.",
    "Analysis detail page: polling, rename, delete, retry, export and streaming chat.",
    "Export route (.txt / .csv / .json) with CSV quote-escaping.",
    "History page: search + pagination.",
    "Compare page: metric overlay chart and prompt generator.",
    "Public access-request API: duplicate detection + validation.",
    "Other API clients (Supabase admin, Resend) already use lazy / in-handler init.",
]))

S.append(Paragraph("Suggested follow-ups (not done this pass)", H1))
S.append(bullets([
    "Dashboard / analysis pages poll every 2.5s while a job runs 10–20 min (hundreds of requests); consider backoff or realtime subscriptions.",
    "No API rate limiting (already noted in README known-limitations).",
    "CSV export could harden against spreadsheet formula injection (low risk — values are AI-generated).",
    "/api/compare-report (OpenAI-backed) appears unused; the Compare UI generates a copy/paste prompt instead. Wire up or remove.",
    "Replace <font face='Courier'>&lt;img&gt;</font> with next/image in the timeline editor to clear the remaining lint warnings.",
]))

S.append(Paragraph("Commit log", H1))
S.append(code_block(
    "a3f53a0  Fix build failure from module-level OpenAI init; add ESLint config\n"
    "f38c22b  Fix navbar brand name (ACA -> Orator) for consistency\n"
    "805dde1  Add app icon and richer metadata (OG, Twitter, noindex)\n"
    "f2ee11a  Replace stale 'ACA' brand name with 'Orator'\n"
    "c1abcb5  Stop tracking tsconfig.tsbuildinfo build cache"))
S.append(HRFlowable(width="100%", color=HexColor("#e4e4e7"), spaceBefore=4, spaceAfter=6))
S.append(Paragraph(
    "All changes pushed to branch <font face='Courier'>claude/relaxed-sagan-reg96i</font>. "
    "Verified with a clean production build (21/21 routes) and a lint pass.", BODY))

doc.build(S)
print("PDF written")
