#!/usr/bin/env python3
"""Generate the change report PDF for the Orator website sweep."""
from fpdf import FPDF
from datetime import date

PURPLE = (124, 58, 237)
DARK = (24, 24, 27)
GREY = (90, 90, 95)
LIGHTGREY = (130, 130, 135)
GREEN = (22, 120, 60)
RED = (170, 40, 40)


def clean(s: str) -> str:
    repl = {
        "—": "-", "–": "-", "→": "->", "‘": "'",
        "’": "'", "“": '"', "”": '"', "…": "...",
        "·": "-", "✓": "[x]", "✕": "x", "é": "e",
        "•": "-",
    }
    for k, v in repl.items():
        s = s.replace(k, v)
    return s.encode("latin-1", "replace").decode("latin-1")


class PDF(FPDF):
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*LIGHTGREY)
        self.cell(0, 8, "Orator - Website Change Report", align="L")
        self.cell(0, 8, f"Page {self.page_no()}", align="R")
        self.ln(10)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*LIGHTGREY)
        self.cell(0, 8, clean("Generated by Claude Code - claude/relaxed-sagan-nvpch5"), align="C")


pdf = PDF(format="A4")
pdf.set_auto_page_break(auto=True, margin=18)
pdf.set_margins(18, 18, 18)
pdf.add_page()

# ---- Title block ----
pdf.set_fill_color(*PURPLE)
pdf.rect(0, 0, 210, 46, "F")
pdf.set_y(14)
pdf.set_font("Helvetica", "B", 22)
pdf.set_text_color(255, 255, 255)
pdf.cell(0, 10, "Website Change Report", ln=1)
pdf.set_font("Helvetica", "", 12)
pdf.cell(0, 7, "Orator - Neural Speech Analysis", ln=1)
pdf.ln(8)
pdf.set_text_color(*GREY)
pdf.set_font("Helvetica", "", 10)
pdf.cell(0, 6, clean(f"Date: {date.today().isoformat()}    Branch: claude/relaxed-sagan-nvpch5    PR: #8"), ln=1)
pdf.ln(4)


def h2(title):
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*PURPLE)
    pdf.cell(0, 8, clean(title), ln=1)
    pdf.set_draw_color(220, 215, 230)
    y = pdf.get_y()
    pdf.line(18, y, 192, y)
    pdf.ln(2)


def body(text):
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*DARK)
    pdf.multi_cell(0, 5.2, clean(text))
    pdf.ln(1)


def item(label, lines, tag=None, tag_color=GREY):
    pdf.set_font("Helvetica", "B", 10.5)
    pdf.set_text_color(*DARK)
    if tag:
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(255, 255, 255)
        pdf.set_fill_color(*tag_color)
        w = pdf.get_string_width(tag) + 4
        pdf.cell(w, 5, tag, align="C", fill=True)
        pdf.cell(2, 5, "")
    pdf.set_font("Helvetica", "B", 10.5)
    pdf.set_text_color(*DARK)
    pdf.multi_cell(0, 5.4, clean(label))
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(*GREY)
    for ln_ in lines:
        pdf.set_x(22)
        pdf.multi_cell(0, 4.8, clean("- " + ln_))
    pdf.ln(1.5)


# ---- Summary ----
h2("Summary")
body(
    "A full sweep of the Orator web app (Next.js 14 App Router, TypeScript, "
    "Tailwind, Supabase). The work fixed a build-breaking bug, two real "
    "security issues, several runtime crashes/glitches, branding "
    "inconsistencies, accessibility gaps, and inaccurate documentation, plus "
    "added standard website polish (error/404 pages, favicon, robots, SEO "
    "metadata). Every change was verified with `next build` and `next lint` "
    "(both green). Delivered as 9 commits on branch claude/relaxed-sagan-nvpch5 "
    "(draft PR #8)."
)
pdf.ln(1)
pdf.set_font("Helvetica", "B", 10)
pdf.set_text_color(*DARK)
pdf.cell(0, 5.5, "By the numbers: 30 files changed, ~674 insertions / 117 deletions, 9 commits.", ln=1)

# ---- Critical / build ----
h2("1. Build & Stability")
item(
    "Production build no longer crashes when OPENAI_API_KEY is absent",
    [
        "OpenAI client was constructed at module load in /api/compare-report and lib/openai.ts.",
        "`next build` failed during page-data collection (e.g. in CI) with a missing-key error.",
        "Now instantiated lazily; compare-report returns a clean 503 when unconfigured.",
        "Files: app/api/compare-report/route.ts, lib/openai.ts",
    ],
    tag="BUILD FIX", tag_color=RED,
)
item(
    "Lint is now runnable in CI",
    [
        "`npm run lint` previously prompted interactively (no ESLint config) and would hang.",
        "Added .eslintrc.json (next/core-web-vitals) and installed the @typescript-eslint",
        "plugin that the source's inline disable comments depend on. Lint passes clean.",
        "Files: .eslintrc.json, package.json",
    ],
    tag="TOOLING", tag_color=GREY,
)
item(
    "Stopped tracking the tsconfig.tsbuildinfo build artifact",
    ["Removed from git and added to .gitignore.", "Files: .gitignore, tsconfig.tsbuildinfo"],
    tag="CLEANUP", tag_color=GREY,
)

# ---- Security ----
h2("2. Security")
item(
    "Fixed reflected XSS in the admin action page",
    [
        "req.name / req.email come from the PUBLIC access-request form and were",
        "interpolated into the admin-facing HTML page without escaping.",
        "A malicious requester could run script in the admin's browser when they",
        "clicked an approve/deny link from email.",
        "Added lib/escapeHtml.ts and escaped all reflected values.",
        "Files: app/api/admin/action/route.ts, lib/escapeHtml.ts",
    ],
    tag="SECURITY", tag_color=RED,
)
item(
    "Escaped user input in all transactional emails",
    [
        "name / email / reason are now HTML-escaped in the notification, approval",
        "and rejection email bodies.",
        "Files: lib/email.ts",
    ],
    tag="SECURITY", tag_color=RED,
)
item(
    "Hardened admin one-click approve/deny tokens",
    [
        "Token signature now verified with a constant-time comparison (timingSafeEqual).",
        "Added validation of the action field and malformed-token guards.",
        "Documented the previously-undocumented ADMIN_ACTION_SECRET - a known fallback",
        "secret otherwise makes the approve/deny links forgeable in production.",
        "Files: lib/adminToken.ts, .env.local.example",
    ],
    tag="SECURITY", tag_color=RED,
)
item(
    "Sanitized chat input forwarded to the model",
    [
        "Only user/assistant string turns (last 20) are forwarded - the client can no",
        "longer inject system messages into the GPT-4o call.",
        "Files: app/api/analyses/[id]/chat/route.ts",
    ],
    tag="SECURITY", tag_color=RED,
)

# ---- Runtime bugs ----
h2("3. Runtime Bug Fixes")
item(
    "Audio waveform no longer flickers during playback",
    [
        "VideoPlayer called Math.random() inside render, re-randomizing 80 bars on every",
        "timeupdate (~4x/sec). Now precomputed once with useMemo (stable, deterministic).",
        "Files: components/VideoPlayer.tsx",
    ],
)
item(
    "Pages no longer hang or crash on failed network requests",
    [
        "analysis detail: fetchDetail wrapped in try/catch - a network error now shows a",
        "message instead of an infinite spinner; rename checks res.ok.",
        "compare: analyses fetch guarded against non-array/error responses (data.filter crash).",
        "admin requests: fetch made resilient so the page does not hang on failure.",
        "editor: delete handlers check res.ok before optimistically removing rows.",
        "Files: analysis/[id]/page.tsx, compare/page.tsx, admin/requests/page.tsx, editor/page.tsx",
    ],
)
item(
    "BrainMap can't crash on out-of-range activation values",
    [
        "Activation is clamped to [0,1]; a negative value previously indexed the color",
        "stops out of bounds and threw.",
        "Files: components/BrainMap.tsx",
    ],
)
item(
    "Chat stream errors are handled gracefully",
    [
        "A mid-stream failure now closes the stream with a message instead of hanging;",
        "returns 503 if OPENAI_API_KEY is unset instead of an opaque 500.",
        "Files: app/api/analyses/[id]/chat/route.ts",
    ],
)

# ---- Admin correctness ----
h2("4. Admin Access Correctness")
item(
    "Admin layout now reads ADMIN_EMAIL from the environment",
    [
        "The /api/admin/* routes read process.env.ADMIN_EMAIL, but the layout hardcoded it.",
        "A deployer who set ADMIN_EMAIL to their own address would pass the API checks yet be",
        "redirected away from the /admin UI. Now consistent.",
        "Files: app/admin/layout.tsx",
    ],
)

# ---- Branding ----
h2("5. Branding Consistency")
item(
    "Replaced leftover 'ACA' branding with 'Orator'",
    [
        "Navbar logo, all transactional emails, and the chat assistant's system prompt",
        "still said 'ACA' while the rest of the product said 'Orator'.",
        "Files: components/Navbar.tsx, lib/email.ts, app/api/analyses/[id]/chat/route.ts",
    ],
)

# ---- A11y ----
h2("6. Accessibility")
item(
    "Form labels associated with their inputs",
    [
        "Added htmlFor/id and autoComplete to the login and request-access forms and the",
        "compare Speech A/B selects (previously visual-only association).",
        "Files: login/page.tsx, request-access/page.tsx, compare/page.tsx",
    ],
)
item(
    "Icon-only buttons given accessible names",
    [
        "aria-labels added to the play/pause, rename, delete and editor-delete buttons.",
        "Files: VideoPlayer.tsx, analysis/[id]/page.tsx, editor/page.tsx",
    ],
)

# ---- Polish / SEO ----
h2("7. Website Polish & SEO")
item(
    "Added standard site infrastructure",
    [
        "Branded 404 (not-found.tsx) and error boundary (error.tsx).",
        "App icon / favicon (app/icon.svg).",
        "robots.txt disallowing all crawlers (app/robots.ts) - invite-only product.",
        "Richer root metadata: OpenGraph tags, robots noindex, theme color, title template.",
        "Files: app/not-found.tsx, app/error.tsx, app/icon.svg, app/robots.ts, app/layout.tsx",
    ],
)
item(
    "Internal navigation uses next/link",
    [
        "Replaced full-page-reload <a> links with <Link> in dashboard, history and admin layout.",
        "Files: dashboard/page.tsx, history/page.tsx, admin/layout.tsx",
    ],
)

# ---- Docs ----
h2("8. Documentation")
item(
    "Corrected TRIBE_SERVER_URL behavior",
    [
        "README and .env.local.example claimed leaving it blank uses mock data, but the",
        "process route errors when it is unset. Mock data is actually produced server-side.",
        "Docs now match the code.",
        "Files: README.md, .env.local.example",
    ],
)

# ---- Verification ----
h2("Verification")
body(
    "After every batch: `npm run build` compiled successfully and `npm run lint` "
    "reported 0 errors (2 pre-existing non-fatal <img> warnings in the Remotion "
    "timeline editor were intentionally left, since next/image is not appropriate "
    "there). TypeScript `tsc --noEmit` passes. All changes pushed to "
    "claude/relaxed-sagan-nvpch5; draft PR #8 opened against main."
)

# ---- Commit log ----
h2("Commit Log")
commits = [
    "Fix build-time OpenAI init, unify branding to Orator, add error/404/icon, a11y",
    "Make lint runnable, use Next Link for internal nav",
    "Fix runtime bugs: waveform flicker, unguarded fetches, BrainMap clamp",
    "Security: escape user input in admin page/emails, harden admin tokens",
    "Accessibility: add aria-labels to icon buttons, associate compare selects",
    "Docs: correct TRIBE_SERVER_URL behavior (required, not blank-for-mock)",
    "Fix admin access: read ADMIN_EMAIL from env in admin layout",
    "Harden chat route: config guard, message sanitization, stream error handling",
    "Add robots.txt (disallow all) and use Link in admin layout",
]
pdf.set_font("Helvetica", "", 9)
pdf.set_text_color(*GREY)
for i, c in enumerate(commits, 1):
    pdf.set_x(20)
    pdf.multi_cell(0, 4.8, clean(f"{i}. {c}"))
    pdf.ln(0.3)

pdf.output("/home/user/speech-analyzer2/Orator-Change-Report.pdf")
print("written")
